Add Certora key and GH Token input validation

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -90,6 +90,18 @@ inputs:
 runs:
   using: "composite"
   steps:
+    - name: Verify Certora key and GitHub Token
+      shell: bash
+      run: |
+        if [[ -z "${{ inputs.certora-key }}" ]]; then
+          echo "::error title=Certora Key is missing::Certora key is required to run the prover jobs. Please provide a valid key as an secret input."
+          exit 1
+        fi
+
+        if [[ -z "$GITHUB_TOKEN" }}" ]]; then
+          echo "::error title=GitHub Token is missing::GitHub token is required for this action. Please provide a valid token as an environment variable."
+          exit 1
+        fi
     - name: Fetch Relevant Commit SHA for the Event
       shell: bash
       run: |
