Use existing solc versions

diff --git a/workflow.yml b/workflow.yml
--- a/workflow.yml
+++ b/workflow.yml
@@ -91,11 +91,17 @@ jobs:
 
       - name: Group ID and Message
         run: |
-          echo "MESSAGE_SUFFIX=${{ github.repository }}@${COMMIT_SHA}" >> $GITHUB_ENV
+          echo "MESSAGE_SUFFIX=${{ github.repository }}/${COMMIT_SHA}" >> $GITHUB_ENV
           echo "GROUP_ID=$(cat /proc/sys/kernel/random/uuid)" >> $GITHUB_ENV
+
+      - name: Cache CLI Dependencies Key
+        run: echo "${{ inputs.cli-version }}-${{ inputs.use-alpha }}-${{ inputs.use-beta }}" > .certora-cache
 
       - name: Install uv
         uses: astral-sh/setup-uv@v4
+        with:
+          enable-cache: true
+          cache-dependency-glob: .certora-cache
 
       - name: Install certora-cli
         run: |
@@ -116,23 +122,34 @@ jobs:
         uses: actions/cache@v4
         with:
           path: /opt/solc-bin
-          key: solc-bin-${{ inputs.solc-versions }}
+          key: solc-bin
 
       - name: Download Solidity Binaries
-        if: steps.solc-cache.outputs.cache-hit != 'true'
         run: |
           mkdir -p /opt/solc-bin
           VERSIONS="${{ inputs.solc-versions }}"
+          GH_LINK='https://api.github.com/repos/ethereum/solidity/releases/tags/v'
+          JQ_FILTER='.assets[] | select(.name == "solc-static-linux") | .url'
+          AUTH_HEADER="Authorization: Bearer ${GITHUB_TOKEN}"
+
           for version in $VERSIONS; do
             version="${version#v}"
             if [ ! -f "/opt/solc-bin/solc$version" ]; then
-              BIN_LINK="$(curl -sH "Authorization: Bearer ${GITHUB_TOKEN}" https://api.github.com/repos/ethereum/solidity/releases/tags/v${version} | jq -r '.assets[] | select(.name == "solc-static-linux") | .url')"
+              echo "Downloading Solidity $version"
+              RELEASE_DETAIL=$(curl -sH "$AUTH_HEADER" "${GH_LINK}${version}")
+              if [[ -z "$RELEASE_DETAIL" || $(jq 'has("assets")' <<< "$RELEASE_DETAIL") == "false" ]]; then
+                echo "Failed to fetch release details for Solidity $version"
+                echo "$RELEASE_DETAIL"
+                exit 1
+              fi
+              BIN_LINK=$(jq -r "$JQ_FILTER" <<< "$RELEASE_DETAIL")
               curl -L \
                 -H "Accept: application/octet-stream" \
-                -H "Authorization: Bearer ${GITHUB_TOKEN}" \
+                -H "$AUTH_HEADER" \
                 "${BIN_LINK}" -o "/opt/solc-bin/solc$version"
             fi
           done
+
           ls -1 /opt/solc-bin/
 
       - name: Add Solidity to Github Path
