Add comments

diff --git a/workflow.yml b/workflow.yml
--- a/workflow.yml
+++ b/workflow.yml
@@ -43,6 +43,18 @@ on:
             0.6.12
             0.7.6
           ```
+      solc-remove-version-prefix:
+        required: false
+        type: string
+        description: |-
+          The prefix to remove from the Solidity version when saving binaries.
+      server:
+        required: true
+        default: production
+        type: string
+        description: |-
+          The server to run the tests on. Default is `production`.
+          Options: `production`, `staging`, or `vaas-dev`.
       use-alpha:
         required: false
         type: boolean
@@ -53,8 +65,15 @@ on:
         type: boolean
         description: |-
           Whether to use the beta version of the `certora-cli`.
+      add-status:
+        required: true
+        default: true
+        type: boolean
+        description: |-
+          Whether to add status checks to the commit.
+
     secrets:
-      certora-key:
+      CERTORAKEY:
         required: true
 
 env:
@@ -87,11 +106,12 @@ jobs:
           else
             COMMIT_SHA="$(git rev-parse HEAD)"
           fi
-          echo "COMMIT_SHA=${COMMIT_SHA:0:12}" >> $GITHUB_ENV
+          echo "COMMIT_SHA=${COMMIT_SHA}" >> $GITHUB_ENV
+          echo "SHORT_COMMIT_SHA=${COMMIT_SHA:0:12}" >> $GITHUB_ENV
 
       - name: Group ID and Message
         run: |
-          echo "MESSAGE_SUFFIX=${{ github.repository }}/${COMMIT_SHA}" >> $GITHUB_ENV
+          echo "MESSAGE_SUFFIX=GH:${{ github.repository }}/${SHORT_COMMIT_SHA}" >> $GITHUB_ENV
           echo "GROUP_ID=$(cat /proc/sys/kernel/random/uuid)" >> $GITHUB_ENV
 
       - name: Cache CLI Dependencies Key
@@ -137,7 +157,13 @@ jobs:
 
           for version in $VERSIONS; do
             version="${version#v}"
-            BIN_PATH="/opt/solc-bin/solc$version"
+            if [ -z "${{ inputs.solc-remove-version-prefix }}" ]; then
+              use_version=$version
+            else
+              use_version="${version#${{ inputs.solc-remove-version-prefix }}}"
+            fi
+
+            BIN_PATH="/opt/solc-bin/solc$use_version"
 
             if [ ! -f "$BIN_PATH" ]; then
               echo "Downloading Solidity $version"
@@ -157,7 +183,7 @@ jobs:
 
               # Verify the binary
               chmod +x "$BIN_PATH"
-              "solc$version" --version
+              "solc$use_version" --version
             fi
           done
 
@@ -174,11 +200,102 @@ jobs:
           done
 
       - name: Run Certora
+        id: certora-run
         run: |
           CONFIGURATIONS="${{ inputs.configurations }}"
+          MAX_MSG_LEN=254
+          SUFFIX_LEN=${#MESSAGE_SUFFIX}
+          REMAINING_LEN=$((MAX_MSG_LEN - SUFFIX_LEN))
+          jobs=0
+
+          LOG_DIR="/tmp/certora-logs/"
+          mkdir -p "$LOG_DIR"
+
           for conf in $CONFIGURATIONS; do
-            echo "Running $conf"
-            uvx --from "$CERT_CLI_PACKAGE" certoraRun $conf --msg "${MESSAGE_SUFFIX}" --group_id "${GROUP_ID}"
+            echo "Starting $conf"
+
+            if [[ ${#conf} -gt $conf_max_length ]]; then
+              msg_conf=${conf: -$REMAINING_LEN}
+            else
+              msg_conf=$conf
+            fi
+
+            # Create log files
+            STDOUT="$LOG_DIR/$conf.stdout"
+            mkdir -p "$(dirname "$STDOUT")"
+            STDERR="$LOG_DIR/$conf.stderr"
+            mkdir -p "$(dirname "$STDERR")"
+
+            uvx --from "$CERT_CLI_PACKAGE" certoraRun \
+              $conf \
+              --msg "${msg_conf} ${MESSAGE_SUFFIX}" \
+              --server "${{ inputs.server }}" \
+              --group_id "${GROUP_ID}" \
+              --send_only \
+              --wait_for_results none >"$STDERR" 2>"$STDERR" &
+
+            ((jobs++)) || true
           done
+
+          # Wait for all jobs to finish and mark if any failed
+          total_ret=0
+          failed_jobs=0
+          for conf in $CONFIGURATIONS; do
+            ret=0
+            wait -n || ret=$?
+            if [ $ret -ne 0 ]; then
+              ((jobs--)) || true
+              ((failed_jobs++)) || true
+              total_ret=$ret
+            fi
+          done
+
+          # Add jobs to output
+          echo "total_jobs=$jobs" >> $GITHUB_OUTPUT
+          echo "failed_jobs=$failed_jobs" >> $GITHUB_OUTPUT
+
+          # Remove empty log files
+          find "$LOG_DIR" -type f -empty -delete
+
+          if [ $ret -ne 0 ]; then
+            echo "Some configurations failed! Please check the logs."
+            exit $ret
+          fi
+
         env:
-          CERTORAKEY: ${{ secrets.certora-key }}
+          CERTORAKEY: ${{ secrets.CERTORAKEY }}
+
+      - name: Add GH Status
+        if: ${{ inputs.add-status }}
+        run: |
+          curl -L \
+            -X POST \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            https://api.github.com/repos/${{ github.repository }}/statuses/$COMMIT_SHA \
+            -d '{"state":"pending","target_url":"https://prover.certora.com","description":"0/${{ steps.certora-run.outputs.total_jobs }} jobs finished.","context":"certora-run"}'
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Upload Logs
+        uses: actions/upload-artifact@v4
+        id: upload-logs
+        if: always()
+        with:
+          name: logs
+          path: /tmp/certora-logs/*
+
+      # Add comment with log link
+      - name: Add Comment With Logs Link
+        if: ${{ steps.upload-logs.outputs.artifact-url }}
+        run: |
+          curl -L \
+            -X POST \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            https://api.github.com/repos/${{ github.repository }}/commits/$COMMIT_SHA/comments \
+            -d '{"body":"# Started Certora Run\n\n- Started ${{ steps.certora-run.outputs.total_jobs }} jobs\n- ${{ steps.certora-run.outputs.failed_jobs }} jobs failed\n\n[Logs](${{ steps.upload-logs.outputs.artifact-url }})\n"}'
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
