Move GH action executions from test repository (#27)
* Move GH action executions from test repository

* Update astral-sh/setup-uv

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -5,7 +5,16 @@ on:
   pull_request:
     branches:
       - main
+      - v*
   workflow_dispatch:
+
+permissions:
+  contents: read
+  statuses: write
+  pull-requests: write
+
+env:
+  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
 jobs:
   syntax-check:
@@ -18,3 +27,70 @@ jobs:
           github_access_token: ${{ secrets.GITHUB_TOKEN }}
       - name: Tests
         run: nix develop --impure --command make check
+
+  fail_to_start:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions/setup-node@v4
+      - run: npm install
+      # TODO: Use dynamic branch version for PRs
+      - uses: Certora/certora-run-action@main
+        with:
+          use-beta: true
+          configurations: |-
+            tests/conf-start-error.conf
+            tests/conf-verified.conf --rule monotone --method "counter()"
+            tests/conf-violations.conf --method "counter()"
+            tests/conf-verified.conf
+            tests/conf-violations.conf --rule invertible
+            tests/conf-start-error.conf --method "counter()"
+          solc-versions: 0.7.6 0.8.1
+          job-name: "Fail to Start"
+          server: "staging"
+          certora-key: ${{ secrets.CERTORAKEY }}
+        id: certora_run
+        continue-on-error: true
+      - name: Check if Fail to Start job failed
+        if: steps.certora_run.outcome != 'failure'
+        run: |
+          echo "Fail to Start job did not fail"
+          exit 1
+
+  violated_rules:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions/setup-node@v4
+      - run: npm install
+      # TODO: Use dynamic branch version for PRs
+      - uses: Certora/certora-run-action@main
+        with:
+          configurations: |-
+            tests/conf-verified.conf
+            tests/conf-violations.conf --rule invertible
+            tests/conf-verified.conf --method "counter()"
+            tests/conf-violations.conf
+          solc-versions: 0.7.6 0.8.1
+          job-name: "Violated Rules"
+          server: "production"
+          certora-key: ${{ secrets.CERTORAKEY }}
+
+  verified_rules:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions/setup-node@v4
+      - run: npm install
+      # TODO: Use dynamic branch version for PRs
+      - uses: Certora/certora-run-action@main
+        with:
+          configurations: |-
+            tests/conf-verified.conf
+            tests/conf-verified.conf --rule monotone --method "counter()"
+            tests/conf-verified.conf --rule invertible
+            tests/conf-verified.conf --method "counter()"
+          solc-versions: 0.7.6 0.8.1
+          job-name: "Verified Rules"
+          server: "vaas-dev"
+          certora-key: ${{ secrets.CERTORAKEY }}
