Fix Local Use (#2)
* Fix local use

* Move wf

* Remove req

* Add GH Token

* Add GH Token

* Remove branch reference

* PR Comment

* Fix typo

* Log file

* Add Comment

* Add Comment

* Debug log

* Fix report file generation

* Fix report file generation

* Fix report file generation

* Use seq

* Use seq

* Iter pids

* More configuration

* More configuration

* Fix config names

* Add more jobs

* Fix logs path

* Add job name

* Add job name

* Correct IDs

* Add groupId to comments

* Add failed report

* Fail jobs

* Add log file to comments

* Add log file to comments

* Fix bash subs

* Add propoer context

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -49,28 +49,26 @@ on:
         description: |-
           The prefix to remove from the Solidity version when saving binaries.
       server:
-        required: true
         default: production
         type: string
         description: |-
           The server to run the tests on. Default is `production`.
           Options: `production`, `staging`, or `vaas-dev`.
       use-alpha:
-        required: false
+        default: false
         type: boolean
         description: |-
           Whether to use the alpha version of the `certora-cli`.
       use-beta:
-        required: false
+        default: false
         type: boolean
         description: |-
           Whether to use the beta version of the `certora-cli`.
-      add-status:
-        required: true
-        default: true
-        type: boolean
+      job-name:
+        default: ${{ github.job }}
+        type: string
         description: |-
-          Whether to add status checks to the commit.
+          The name of the job. Default is the name of the job that called this workflow.
 
     secrets:
       CERTORAKEY:
@@ -78,14 +76,14 @@ on:
 
 env:
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  LOG_DIR: /tmp/certora-logs/
+  REPORT_FILE: /tmp/certora-logs/REPORT.md
 
 jobs:
   certora_run:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-        with:
-          ref: feat/initial-setup
       - name: Fetch Relevant Commit SHA for the Event
         run: |
           COMMIT_SHA=""
@@ -110,9 +108,12 @@ jobs:
           echo "SHORT_COMMIT_SHA=${COMMIT_SHA:0:12}" >> $GITHUB_ENV
 
       - name: Group ID and Message
+        id: group-id
         run: |
           echo "MESSAGE_SUFFIX=GH:${{ github.repository }}/${SHORT_COMMIT_SHA}" >> $GITHUB_ENV
-          echo "GROUP_ID=$(cat /proc/sys/kernel/random/uuid)" >> $GITHUB_ENV
+          GROUP_ID="$(cat /proc/sys/kernel/random/uuid)"
+          echo "GROUP_ID=$GROUP_ID" >> $GITHUB_ENV
+          echo "group_id=$GROUP_ID" >> $GITHUB_OUTPUT
 
       - name: Cache CLI Dependencies Key
         run: echo "${{ inputs.cli-version }}-${{ inputs.use-alpha }}-${{ inputs.use-beta }}" > .certora-cache
@@ -202,51 +203,65 @@ jobs:
       - name: Run Certora
         id: certora-run
         run: |
+          set -ex
           CONFIGURATIONS="${{ inputs.configurations }}"
           MAX_MSG_LEN=254
           SUFFIX_LEN=${#MESSAGE_SUFFIX}
           REMAINING_LEN=$((MAX_MSG_LEN - SUFFIX_LEN))
           jobs=0
 
-          LOG_DIR="/tmp/certora-logs/"
           mkdir -p "$LOG_DIR"
 
+          pids=()
+          configs=()
+          logs=()
           for conf in $CONFIGURATIONS; do
-            echo "Starting $conf"
-
-            if [[ ${#conf} -gt $conf_max_length ]]; then
-              msg_conf=${conf: -$REMAINING_LEN}
+            if [[ ${#conf} -gt $MAX_MSG_LEN ]]; then
+              MSG_CONF="${conf: -$REMAINING_LEN}"
             else
-              msg_conf=$conf
+              MSG_CONF="$conf"
             fi
+            echo "Starting $conf with message: $MSG_CONF"
 
             # Create log files
-            STDOUT="$LOG_DIR/$conf.stdout"
-            mkdir -p "$(dirname "$STDOUT")"
-            STDERR="$LOG_DIR/$conf.stderr"
-            mkdir -p "$(dirname "$STDERR")"
+            RAND_SUFF=$(openssl rand -hex 6)
+            LOG_FILE="$(printf "%s" "${LOG_DIR}${conf}-${RAND_SUFF}.log" | tr -s '/')"
+            mkdir -p "$(dirname "$LOG_FILE")"
+            logs+=("$LOG_FILE")
 
             uvx --from "$CERT_CLI_PACKAGE" certoraRun \
               $conf \
-              --msg "${msg_conf} ${MESSAGE_SUFFIX}" \
+              --msg "${MSG_CONF} ${MESSAGE_SUFFIX}" \
               --server "${{ inputs.server }}" \
               --group_id "${GROUP_ID}" \
               --send_only \
-              --wait_for_results none >"$STDERR" 2>"$STDERR" &
+              --wait_for_results none >"$LOG_FILE" 2>&1 &
+            pids+=($!)
+            configs+=($conf)
 
             ((jobs++)) || true
           done
 
+          echo "My pids (length ${#pids[@]})): ${pids[@]}"
+
+          echo "## Certora Run Started (${{ inputs.job-name }})" > "$REPORT_FILE"
+          echo "- Group ID: $GROUP_ID" >> "$REPORT_FILE"
+          echo "" >> $REPORT_FILE
+          echo "| Config | Status | Link | Log File |" >> "$REPORT_FILE"
+          echo "|--------|--------|------|----------|" >> "$REPORT_FILE"
+
           # Wait for all jobs to finish and mark if any failed
-          total_ret=0
           failed_jobs=0
-          for conf in $CONFIGURATIONS; do
+          for i in "${!pids[@]}"; do
             ret=0
-            wait -n || ret=$?
-            if [ $ret -ne 0 ]; then
+            wait "${pids[i]}" || ret=$?
+            if [[ $ret -ne 0 ]]; then
               ((jobs--)) || true
               ((failed_jobs++)) || true
-              total_ret=$ret
+              echo "| ${configs[i]} | Failed ($ret) | - | ${logs[i]#$LOG_DIR} |" >> "$REPORT_FILE"
+            else
+              LINK=$(grep -oE "https://(vaas-dev|vaas-stg|prover)\.certora\.com/[^/]+/[0-9]+/[a-zA-Z0-9-]+/?.*\?.*anonymousKey=[a-zA-Z0-9-]+" "${logs[i]}" || true)
+              echo "| ${configs[i]} | Submited | [link]($LINK) | ${logs[i]#$LOG_DIR} |" >> "$REPORT_FILE"
             fi
           done
 
@@ -257,16 +272,16 @@ jobs:
           # Remove empty log files
           find "$LOG_DIR" -type f -empty -delete
 
-          if [ $ret -ne 0 ]; then
+          if [[ $failed_jobs -ne 0 ]]; then
             echo "Some configurations failed! Please check the logs."
-            exit $ret
+            exit 1
           fi
 
         env:
           CERTORAKEY: ${{ secrets.CERTORAKEY }}
 
       - name: Add GH Status
-        if: ${{ inputs.add-status }}
+        if: always()
         run: |
           curl -L \
             -X POST \
@@ -274,7 +289,7 @@ jobs:
             -H "Authorization: Bearer ${GITHUB_TOKEN}" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             https://api.github.com/repos/${{ github.repository }}/statuses/$COMMIT_SHA \
-            -d '{"state":"pending","target_url":"https://prover.certora.com","description":"0/${{ steps.certora-run.outputs.total_jobs }} jobs finished.","context":"certora-run"}'
+            -d '{"state":"pending","target_url":"https://prover.certora.com","description":"0/${{ steps.certora-run.outputs.total_jobs }} jobs finished.","context":"certora-run/${{ steps.group-id.outputs.group_id }}"}'
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
@@ -283,19 +298,21 @@ jobs:
         id: upload-logs
         if: always()
         with:
-          name: logs
+          name: certora-run-logs-${{ steps.group-id.outputs.group_id }}-${{ github.run_id }}
           path: /tmp/certora-logs/*
 
-      # Add comment with log link
-      - name: Add Comment With Logs Link
-        if: ${{ steps.upload-logs.outputs.artifact-url }}
+      - name: Add Summary To Report
+        if: always()
         run: |
-          curl -L \
-            -X POST \
-            -H "Accept: application/vnd.github+json" \
-            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            https://api.github.com/repos/${{ github.repository }}/commits/$COMMIT_SHA/comments \
-            -d '{"body":"# Started Certora Run\n\n- Started ${{ steps.certora-run.outputs.total_jobs }} jobs\n- ${{ steps.certora-run.outputs.failed_jobs }} jobs failed\n\n[Logs](${{ steps.upload-logs.outputs.artifact-url }})\n"}'
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          echo "### Certora Run Summary" >> $REPORT_FILE
+          echo "- Started ${{ steps.certora-run.outputs.total_jobs }} jobs" >> $REPORT_FILE
+          echo "- ${{ steps.certora-run.outputs.failed_jobs }} jobs failed" >> $REPORT_FILE
+          echo "" >> $REPORT_FILE
+          echo "[Download Logs](${{ steps.upload-logs.outputs.artifact-url }})" >> $REPORT_FILE
+
+      - name: Add report comment
+        if: always()
+        uses: mshick/add-pr-comment@v2
+        with:
+          message-id: ${{ steps.group-id.outputs.group_id }}
+          message-path: ${{ env.REPORT_FILE }}
